import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h3>基于next搭建一个适用于移动端的h5模板</h3>
        <div>使用到的库如下: </div>
        <ul className={inter.className}>
          <li>1.eslint</li>
          <li>2.prettier</li>
          <li>3.husky</li>
        </ul>
      </main>
    </>
  )
}
