import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
import styles from './Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Your Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h3 className={styles.title}>基于next搭建一个适用于移动端的h5模板</h3>
        <div className={styles.desc}>使用到的库如下: </div>
        <ul className={styles.inter}>
          <li className={styles.liItem}>1.eslint</li>
          <li className={styles.liItem}>2.prettier</li>
          <li className={styles.liItem}>3.husky</li>
          <li className={styles.liItem}>4.postcss-pxtorem</li>
        </ul>
      </main>
    </>
  )
}
